Warning: 100 points required, but 256 points sampled.
Warning: 10000 points required, but 25600 points sampled.
Compiling model...
'compile' took 3.515562 s

Training model...
Error executing job with overrides: []
Traceback (most recent call last):
  File "/working_dir/./src/main.py", line 54, in main
    train.single_observer(prj, cfg.run, "0", cfg)
  File "/working_dir/src/train.py", line 109, in single_observer
    mo = train_model(run, cfg)
  File "/working_dir/src/train.py", line 46, in train_model
    mm = pde.create_nbho(name, cfg)
  File "/working_dir/src/pde.py", line 224, in create_nbho
    initial_losses = train.get_initial_loss(model)
  File "/working_dir/src/train.py", line 154, in get_initial_loss
    losshistory, _ = model.train(0)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 636, in train
    self._test()
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 825, in _test
    ) = self._outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 546, in _outputs_losses
    outs = outputs_losses(inputs, targets, auxiliary_vars)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 320, in outputs_losses_train
    return outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 308, in outputs_losses
    losses = losses_fn(targets, outputs_, loss_fn, inputs, self, aux=aux)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/data/data.py", line 13, in losses_train
    return self.losses(targets, outputs, loss_fn, inputs, model, aux=aux)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/data/pde.py", line 175, in losses
    error = bc.error(self.train_x, inputs, outputs, beg, end)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/icbc/initial_conditions.py", line 30, in error
    values = self.func(X, beg, end, aux_var)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/icbc/boundary_conditions.py", line 391, in wrapper_cache
    cache[key] = func(X[beg:end])
  File "/opt/conda/lib/python3.10/site-packages/deepxde/utils/internal.py", line 87, in wrapper
    return bkd.as_tensor(func(*args, **kwargs), dtype=config.real(bkd.lib))
  File "/working_dir/src/pde.py", line 184, in ic_obs
    return (cfg.data.q0 * x[:, 0]**4)/(4*(cfg.data.Tmax - cfg.data.Tmin))
omegaconf.errors.ConfigAttributeError: Key 'q0' is not in struct
    full_key: data.q0
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
